set -sg escape-time 500
set -g mouse on
setw -g window-size latest

set -g status-style 'bg=colour235,fg=colour245'
set -g status-left '#[fg=colour252,bold] #S #[default]| '
set -g status-left-length 60
set -g status-right '#{?client_readonly,#[fg=red bold]READ ONLY #[default]| ,}#{?pane_input_off,#[fg=red bold]INPUT OFF #[default]| ,}#{?pane_in_mode,#[fg=yellow]#{pane_mode} #[default]| ,}#{?window_zoomed_flag,#[fg=cyan]ZOOM #[default]| ,}#{?client_prefix,#[fg=cyan]PREFIX #[default]| ,}#H | %H:%M '
set -g status-right-length 120
set -g status-justify left
set -g status-interval 5

setw -g window-status-format ' #I:#W '
setw -g window-status-current-format ' #I:#W '
setw -g window-status-style 'bg=colour235,fg=colour245'
setw -g window-status-current-style 'bg=cyan,fg=colour235,bold'
setw -g window-status-separator ''
