[keybindings]
new-tab='<Primary><Shift>t'
close-tab='<Primary><Shift>w'
new-window='<Primary><Shift>n'
next-tab='<Primary>Tab'
prev-tab='<Primary><Shift>Tab'
move-tab-left='<Primary><Shift>Left'
move-tab-right='<Primary><Shift>Right'
switch-to-tab-1='<Primary><Alt>1'
switch-to-tab-2='<Primary><Alt>2'
switch-to-tab-3='<Primary><Alt>3'
switch-to-tab-4='<Primary><Alt>4'
switch-to-tab-5='<Primary><Alt>5'
switch-to-tab-6='<Primary><Alt>6'
switch-to-tab-7='<Primary><Alt>7'
switch-to-tab-8='<Primary><Alt>8'
switch-to-tab-last='<Primary><Alt>9'
copy='<Primary><Shift>c'
paste='<Primary><Shift>v'
find='<Primary><Shift>f'
reset-and-clear='<Primary><Shift>k'
