[Shortcuts]
new-tab='<ctrl><shift>t'
close-tab='<ctrl><shift>w'
new-window='<ctrl><shift>n'
move-next-tab='<ctrl>Tab'
move-previous-tab='<ctrl><shift>Tab'
move-tab-left='<ctrl><shift>Left'
move-tab-right='<ctrl><shift>Right'
focus-tab-1='<ctrl><alt>1'
focus-tab-2='<ctrl><alt>2'
focus-tab-3='<ctrl><alt>3'
focus-tab-4='<ctrl><alt>4'
focus-tab-5='<ctrl><alt>5'
focus-tab-6='<ctrl><alt>6'
focus-tab-7='<ctrl><alt>7'
focus-tab-8='<ctrl><alt>8'
focus-tab-last='<ctrl><alt>9'
copy-clipboard='<ctrl><shift>c'
paste-clipboard='<ctrl><shift>v'
search='<ctrl><shift>f'
set-title='<shift><alt>r'
